env_config:
    env_name: MiniGrid-FourRooms-v0 #MiniGrid-FourRooms-Continuous-v0 #MiniGrid-GoToDoor-5x5-v0 #MiniGrid-DoorKey-5x5-v0 #MiniGrid-Empty-5x5-v0
framework: torch
seed: 123
gamma: 0.995
lr: 0.0003
num_workers: 20 #15
# vf_loss_coeff: 0.01
num_sgd_iter: 3 #3 id for default training dataset
sgd_minibatch_size:  512 
train_batch_size:  10000 
# observation_filter: MeanStdFilter
model:
    # use_lstm: true
    conv_activation: relu
    dim: 7
    # grayscale: true
    # zero_mean: false
    # Reduced channel depth and kernel size from default
    fcnet_hiddens: [256, 256]
    fcnet_activation: relu
    conv_filters: [
        [32, [2, 2], 1],
        [32, [2, 2], 2],
        [32, [2, 2], 2],
        [32, [2, 2], 2],
    ]
output: "/root/dev_ws/offline_dataset/ppo_fourrooms_continuous_notfilter"
output_max_file_size: 500000000 #500m