env_config:
    env_name: MiniGrid-KeyCorridorS4R3-v0 #MiniGrid-GoToDoor-5x5-v0 #MiniGrid-DoorKey-5x5-v0 #MiniGrid-Empty-5x5-v0
framework: torch
seed: 12345
gamma: 0.995
lr: 0.00005
train_batch_size: 640000 #320000 
sgd_minibatch_size: 1024 
num_sgd_iter: 2
rollout_fragment_length: 500
num_workers: 20 #20
num_envs_per_worker: 5 #5
num_gpus: 2
model:
    # use_lstm: true
    conv_activation: relu
    dim: 7
    fcnet_hiddens: [256, 256]
    fcnet_activation: relu
    conv_filters: [
        [32, [2, 2], 1],
        [32, [2, 2], 2],
        [32, [2, 2], 2],
        [32, [2, 2], 2],
    ]
output: "/root/dev_ws/offline_dataset/ppo_corridor_nofilter"
output_max_file_size: 500000000 #500m