env_config:
    env_name: MiniGrid-GoToDoor-5x5-v0 #MiniGrid-DoorKey-5x5-v0 #MiniGrid-Empty-5x5-v0
framework: torch
gamma: 0.99
lr: 0.0003
num_workers: 5
model:
    conv_filters: [
    [32, [7, 7], 3],
    [32, [3, 3], 3],
    ]